# -*- coding: utf-8 -*-
"""INFOMTALC2026_Midterm_Chess_6672582.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmeDoz3FEjM_2m-4ezN3WLi6YTMet1My

# Assignment

defs :
0. tokenazation
1. token embeddings,
2. positional embeddings,
3. embedding layer
4. decoder block,
5. putting it all together
6. code for text generation
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/bylinina/chess_exam.git
# %cd /content/chess_exam
!pip install -e .

from chess_tournament import (
    Game,
    Player,
    RandomPlayer,
    LMPlayer,
    SmolPlayer,
    EnginePlayer,
    run_tournament
    )

import torch
import torch.nn as nn
import chess
import random
from transformers import GPT2Tokenizer, GPT2LMHeadModel, GPT2TokenizerFast
import pandas as pd

"""# 0. Tokenization

id's are given
"""

# loading the pre-trained tokenizer
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

from transformers import GPT2TokenizerFast
from tokenizers.processors import TemplateProcessing

# loading the pre-trained tokenizer
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

# here, we are updating the tokenizer to add EOS token at the end of a sequence
tokenizer._tokenizer.post_processor = TemplateProcessing(
    single=f"$A:0 {tokenizer.eos_token}:0",          # Pattern for single sentences: "Text + EOS"
    pair=f"$A:0 {tokenizer.eos_token}:0 $B:1 {tokenizer.eos_token}:1", # Pattern for pairs (not used here)
    special_tokens=[
        (tokenizer.eos_token, tokenizer.eos_token_id),
    ])

# Critical: GPT-2 tokenizer doesn't have a default PAD token.
# (we'll talk more about PAD token below)
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids("[PAD]")

"""# 1. token embeddings

id's are replaced by numbers representing relationships
"""

import torch
from torch import nn

class TokenEmbedding(nn.Module):

  def __init__(self, vocab_size, model_dim):
    super().__init__()

    #intialize the token embedding layer
    self.token_embeddings = nn.Embedding(vocab_size, model_dim)

  def forward(self, x):
    t_embed = self.token_embeddings(x)
    return t_embed

"""# 2. positional embeddings Nieuwe sectie

embeddings for word positions
"""

class PositionalEmbedding(nn.Module):
  def __init__(self, max_length, model_dim):
    super().__init__()
    self.positional_embeddings = nn.Embedding(max_length, model_dim)

  def forward(self, x):
    #input_ids shape -> [batch_size, sequence_length]
    seq_length = x.shape[1]
    pos_embed = self.positional_embeddings(
        torch.arange(seq_length, device=x.device)
    )
    #we need to make the shape [1, sequence_length]
    pos_embed = pos_embed.unsqueeze(0) #shape -> [1, sequence_length]
    return pos_embed

"""# 3. embedding layer
(combine token embeddings and positional embeddings)
"""

class EmbeddingLayer(nn.Module):
  def __init__(self, vocab_size, model_dim, max_length):
    super().__init__()
    self.token_embeddings = TokenEmbedding(vocab_size, model_dim)
    self.positional_embeddings = PositionalEmbedding(max_length, model_dim)

    #something extra we add for mumerical stability
    self.layer_norm = nn.LayerNorm(model_dim)

  def forward(self, input_ids):
    token_embeddings = self.token_embeddings(input_ids) #shape -> [batch_size, sequence_length, model_dim]
    positional_embeddings = self.positional_embeddings(input_ids) #shape -> [1, sequence_length, model_dim]

    #here, we combine the two types of embeddings via addition
    #as you see above, the shape of these tensors doesn't match
    #here, pytorch broadcasting comes into play
    #positional embedding gets broadcasted to the first dimension (batch_size)
    embeddings = token_embeddings + positional_embeddings
    embeddings = self.layer_norm(embeddings)
    return embeddings

"""# 4. decoder block
tensor of embeddings (token+positional) is put into decoder block

4.1 multi-head attention layer

causal masked self attention, a special type of attention for decoders

a) self attention

query = the information a token is looking for

key = the information a token contains

value = the actual information that will be passed along
"""

import torch.nn.functional as F
import math

class SelfAttentionHead(nn.Module):
    def __init__(self, model_dim, head_dim, max_length, dropout=0.1):
        super().__init__()
        #we intialize the WQ, WK and WV matrices.
        #you may wonder why didnt we initialize them using Pytorch Tensors
        #it's because we want the model to learn the behaviour of query, key, value during training
        #so, we use torch.nn.Linear layers which contain learnable torch tensors inside
        self.query = nn.Linear(model_dim, head_dim, bias=False)
        self.key   = nn.Linear(model_dim, head_dim, bias=False)
        self.value = nn.Linear(model_dim, head_dim, bias=False)

        #this component guarantees causal attention
        #it creates a lower traingular matrix of ones
        self.register_buffer("tril", torch.tril(torch.ones(max_length, max_length)))

        #dropout randomly sets a fraction of neuron outputs to 0 during training
        #this forces the model to learn more robust features
        #during inference, dropout is turned off
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x shape: [batch_size, sequence_length, model_dim]
        B, T, C = x.shape

        #calculate Q, K, V
        q = self.query(x) # [B, T, head_dim]
        k = self.key(x)   # [B, T, head_dim]
        v = self.value(x) # [B, T, head_dim]

        #calculate Attention Scores (weights)
        #formula: (Q @ K^T) / sqrt(d_k)
        #transpose k to match dimensions: [B, T, head_dim] -> [B, head_dim, T]
        weights = q @ k.transpose(-2, -1) * (1.0 / math.sqrt(k.size(-1))) # [B, T, T]

        #apply Causal Mask (The "Decoder" part)
        #we mask out the upper triangle so tokens can't see the future
        #"masked_fill" replaces 0s in the tril with -infinity
        weights = weights.masked_fill(self.tril[:T, :T] == 0, float('-inf'))

        #normalize scores to probabilities
        weights = F.softmax(weights, dim=-1)
        weights = self.dropout(weights)

        #aggregate values
        # Formula: weights @ V
        out = weights @ v # [B, T, head_dim]

        return out

"""
b) multi-head attention"""

class MultiHeadAttention(nn.Module):
    def __init__(self, model_dim, num_heads, max_length, dropout=0.1):
        super().__init__()

        #we assume model_dim is divisible by num_heads (e.g., 768 / 12 = 64)
        head_dim = model_dim // num_heads

        #we create a list of independent SelfAttentionHead layers
        #nn.ModuleList is required so PyTorch registers them as sub-modules
        self.heads = nn.ModuleList([
            SelfAttentionHead(model_dim, head_dim, max_length, dropout)
            for _ in range(num_heads)
        ])

        #the final projection layer to mix the results from all heads
        self.output_linear = nn.Linear(model_dim, model_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        #run each head independently
        #each head returns [Batch, Seq_Len, head_dim]
        head_outputs = [head(x) for head in self.heads]

        #concatenate them along the last dimension (head_dim)
        #result shape: [Batch, Seq_Len, model_dim]
        out = torch.cat(head_outputs, dim=-1)

        #project and apply dropout
        out = self.output_linear(out)
        out = self.dropout(out)

        return out

"""
4.2 feed forward layer
"""

class FeedForward(nn.Module):
    def __init__(self, model_dim, dropout=0.1):
        super().__init__()
        #we expand the representation
        self.linear1 = nn.Linear(model_dim, 4 * model_dim)

        # 2. Activation: GPT-2 uses GELU (Gaussian Error Linear Unit)
        # It's a smoother version of ReLU that helps with training deep networks
        self.gelu = nn.GELU()

        #contract: Project back down to model_dim
        self.linear2 = nn.Linear(4 * model_dim, model_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x shape: [Batch, Seq_Len, Model_Dim]
        x = self.linear1(x)
        x = self.gelu(x)
        x = self.linear2(x)
        x = self.dropout(x)
        return x

class DecoderBlock(nn.Module):
    def __init__(self, model_dim, num_heads, max_length, dropout=0.1):
        super().__init__()

        # First Layer Norm
        self.layer_norm1 = nn.LayerNorm(model_dim)
        # Multi-Head Attention
        self.attention = MultiHeadAttention(model_dim, num_heads, max_length, dropout)
        # Second Layer Norm
        self.layer_norm2 = nn.LayerNorm(model_dim)
        # Feed Forward Network
        self.feed_forward = FeedForward(model_dim, dropout)

    def forward(self, x):
      x = self.layer_norm1(x)
      x = self.attention(x)
      x = self.layer_norm2(x)
      x = self.feed_forward(x)

      return x

"""# 5. MiniGPT"""

class MiniGPT(nn.Module):
    def __init__(self, vocab_size, model_dim, max_length, num_heads, num_layers, dropout=0.1):
        super().__init__()

        #embeddings
        self.embeddings = EmbeddingLayer(vocab_size, model_dim, max_length)
        self.emb_dropout = nn.Dropout(dropout)

        #the transformer stack
        #we stack 'num_layers' DecoderBlocks
        self.blocks = nn.ModuleList([
            DecoderBlock(model_dim, num_heads, max_length, dropout)
            for _ in range(num_layers)
        ])

        #final layer norm (standard in gpt-2)
        self.ln_f = nn.LayerNorm(model_dim)

        #language model head
        #projects from model_dim back to vocab_size to predict the next token
        self.lm_head = nn.Linear(model_dim, vocab_size, bias=False)

        #initialize weights
        self.apply(self._init_weights)

    def _init_weights(self, module):
        #standard gpt-2 initialization
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, input_ids):
        #embeddings
        x = self.embeddings(input_ids)
        x = self.emb_dropout(x)

        #run through all transformer blocks
        for block in self.blocks:
            x = block(x)

        #final norm
        x = self.ln_f(x)

        #predict logits (scores for next token)
        logits = self.lm_head(x)

        return logits

"""# 6. Model training"""

# ---------------------------------------------------------
# 1) Install + import
# ---------------------------------------------------------
!pip install datasets

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from datasets import load_dataset
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from transformers import GPT2TokenizerFast

dataset = load_dataset("bonna46/Chess-FEN-and-NL-Format-30K-Dataset", split="train")
input_text = [f"{row['FEN']} {row['Next move']}" for row in dataset]

# clean constants at the top so they are easy to change
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 64
LEARNING_RATE = 3e-4
EPOCHS = 5
LOG_INTERVAL = 400

def train_model(model, dataset, tokenizer):
    # move model to gpu
    model = model.to(DEVICE) # Ensure model is on the correct device
    model.train() # set to training mode (enables dropout)

    # 2. setup optimizer and loss
    # AdamW is the standard for transformers
    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)

    # ignore_index tells pytorch to not calculate error for padding tokens
    criterion = nn.CrossEntropyLoss(ignore_index=tokenizer.pad_token_id)

    # create dataloader
    dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    print(f"Starting training on {DEVICE}...")

    # 3. the training loop
    for epoch in range(EPOCHS):
        model.train()
        for step, batch in enumerate(dataloader):

            # move data to device
            # batch is just input_ids because of your dataset class
            input_ids = batch.to(DEVICE) # shape: [batch, seq_len]

            # forward pass
            # get the raw unnormalized scores
            logits = model(input_ids) # shape: [batch, seq_len, vocab_size]

            # shift logits and targets
            # we need to align the prediction at position 't' with the actual token at 't+1'

            # remove the last prediction (we don't have a target for it)
            shift_logits = logits[..., :-1, :].contiguous()

            # remove the first token (we don't predict it)
            shift_targets = input_ids[..., 1:].contiguous()

            # calculate loss
            # flatten both tensors to [batch * (seq_len-1)]
            loss = criterion(
                shift_logits.view(-1, shift_logits.size(-1)),
                shift_targets.view(-1)
            )

            # backpropagation
            optimizer.zero_grad() # reset previous gradients
            loss.backward()       # calculate new gradients
            optimizer.step()      # update weights

            # logging
            if step % LOG_INTERVAL == 0:
                print(f"Epoch {epoch} | Step {step} | Loss: {loss.item():.4f}")
                prompt = "The little boy was hungry"
                generated_story = generate_text(model, tokenizer, prompt, max_new_tokens=20, temperature=1.0)
                print("-" * 50)
                print(generated_story)
                print("-" * 50)

    print("Training complete!")
    return model

from torch.utils.data import Dataset
from typing import Optional

class PrepDataset(Dataset):
    def __init__(self, tokenizer, dataset, max_length=128):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.dataset = dataset

    def __len__(self):
            return len(self.dataset)

    def __getitem__(self, idx):
        text = self.dataset[idx]['text']

        encodings = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )
        return encodings['input_ids'].squeeze(0)

#parameters
vocab_size = len(tokenizer)
max_length = 128
model_dim = 256
num_layers = 6 #this is the number Decoder Blocks
num_heads = 8
dropout = 0.1

#prep data
train_dataset = PrepDataset(tokenizer, dataset, max_length=max_length)

#intialize the model
model = MiniGPT(vocab_size, model_dim, max_length, num_heads, num_layers, dropout)
torch.save(model.state_dict(), "trained_model.pt")

"""# TransformerPlayer

class Player(ABC):
    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def get_move(self, fen: str) -> Optional[str]:
        pass
"""

class Jasmijn(Player):

    def __init__(self, name):
      super().__init__(name)
      self.tokenizer = self.tokenizer()
      self.model = self.model()
      self.model.load_state_dict(torch.load("trained_model.pt", map_location="cpu"))
      self.model.eval()



    def tokenizer(self):
        # loading the pre-trained tokenizer
        tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

        # here, we are updating the tokenizer to add EOS token at the end of a sequence
        tokenizer._tokenizer.post_processor = TemplateProcessing(
            single=f"$A:0 {tokenizer.eos_token}:0",          # Pattern for single sentences: "Text + EOS"
            pair=f"$A:0 {tokenizer.eos_token}:0 $B:1 {tokenizer.eos_token}:1", # Pattern for pairs (not used here)
            special_tokens=[
                (tokenizer.eos_token, tokenizer.eos_token_id),
            ])

        # Critical: GPT-2 tokenizer doesn't have a default PAD token.
        # (we'll talk more about PAD token below)
        tokenizer.add_special_tokens({'pad_token': '[PAD]'})
        tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids("[PAD]")

        return tokenizer

    def model(self):
        #parameters
        vocab_size = len(tokenizer)
        max_length = 128
        model_dim = 256
        num_layers = 6 #this is the number Decoder Blocks
        num_heads = 8
        dropout = 0.1

        #prep data
        train_dataset = PrepDataset(tokenizer, dataset, max_length=max_length)

        #intialize the model
        model = MiniGPT(vocab_size, model_dim, max_length, num_heads, num_layers, dropout)

        return model

    def get_move(self, fen: str) -> Optional[str]:
        tokenizer = self.tokenizer()
        model = self.model()

        inputs = tokenizer(fen, return_tensors="pt")
        outputs = model.generate(**inputs)
        move = tokenizer.decode(outputs[0], skip_special_tokens=True)

        return move

from transformers import GPT2TokenizerFast
from tokenizers.processors import TemplateProcessing


# loading the pre-trained tokenizer
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

# here, we are updating the tokenizer to add EOS token at the end of a sequence
tokenizer._tokenizer.post_processor = TemplateProcessing(
    single=f"$A:0 {tokenizer.eos_token}:0",          # Pattern for single sentences: "Text + EOS"
    pair=f"$A:0 {tokenizer.eos_token}:0 $B:1 {tokenizer.eos_token}:1", # Pattern for pairs (not used here)
    special_tokens=[
        (tokenizer.eos_token, tokenizer.eos_token_id),
    ])

# Critical: GPT-2 tokenizer doesn't have a default PAD token.
# (we'll talk more about PAD token below)
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids("[PAD]")

"""# Test"""

random1 = Jasmijn("Random-1")
random2 = RandomPlayer("Random-2")

game = Game(random1, random2, max_half_moves=50)
game.play(log_moves=True, log_to_file='log.csv')
